Resources:
  CustomerEndpointsTable:
    DeletionPolicy: Delete
    Type: "AWS::DynamoDB::Table"
    Properties:
      Tags:
        - Key: env
          Value: ${sls:stage}
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: ownerId
          AttributeType: S
        - AttributeName: endpointId
          AttributeType: S
      KeySchema:
        - AttributeName: ownerId
          KeyType: HASH
        - AttributeName: endpointId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.base}-endpoints
